#!/bin/bash

BACKUP=/mnt/data/Backup

if [[ ! -e $BACKUP ]]; then
  mkdir -p $BACKUP
fi

if [[ -f $BACKUP ]]; then
  echo "$BACKUP is a file, expected a directory. Exiting..."
  exit 1
fi


BackupDir () {
  if [[ -d $1 ]]; then
    cp -r $1 $BACKUP
  fi
}

BackupDir $HOME/.openssh
BackupDir $HOME/.config/tmuxinator
