#!/bin/bash

WALLPAPER="/mnt/data/Pictures/Wallpapers/827259.png"


if [[ -x $HOME/Projects/oss/i3lock-multimonitor/lock ]]; then
    exec $HOME/Projects/oss/i3lock-multimonitor/lock -i $WALLPAPER -a "--pointer=default --show-failed-attempts"
else
    exec i3lock --image=$WALLPAPER --show-failed-attempts --pointer=default
fi
