#!/bin/bash

# Output current version
livebook --version

# Remove the existing livebook shim: 
rm $HOME/.asdf/shims/livebook
# Install the new version: 
mix escript.install hex livebook
# Re-shim to get the command: 
asdf reshim elixir
# Verify you have the upgrade: 
livebook --version
