#!/bin/bash

if type podman >/dev/null; then
    PROGRAM=podman
else
    PROGRAM=docker
fi

mkdir -p $HOME/docker/volumes/postgres

$PROGRAM run --rm  --name pg-docker -e POSTGRES_PASSWORD=docker -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data postgres
