#!/bin/bash

if type podman >/dev/null 2>&1; then
    PROGRAM=podman
else
    PROGRAM=docker
fi

VOLUME=postgres

$PROGRAM volume create $VOLUME

$PROGRAM run --rm  --name pg-docker -e POSTGRES_PASSWORD=docker -p 5432:5432 -v $VOLUME:/var/lib/postgresql/data:O postgres
