#!/bin/bash

# Increase volume
# exec pactl set-sink-volume @DEFAULT_SINK@ $(printf "%s\n" 100 $(($(pacmd dump-volumes | grep -m1 Sink | grep -Po '\d+(?=%)' | head -n1) + 3)) | sort -g | head -n1)%

exec pactl set-sink-volume @DEFAULT_SINK@ +3%
