#!/bin/bash

FULL_PATH=$(readlink -e "$@")

if [[ ! -e "$FULL_PATH" ]]; then
    exit 1
fi

WALLPAPER=$HOME/.config/sway/wallpaper

ln -sf "$FULL_PATH" "$WALLPAPER"
exec swaymsg "output * bg $WALLPAPER fill"
