#!/bin/bash

exec swaynag -c $HOME/.config/sway/swaynag -t solarized_light -m 'Power Menu Options' \
    -b 'Logout' 'swaymsg exit' \
    -b 'Suspend' 'systemctl suspend' \
    -b 'Reboot' 'systemctl reboot' \
    -b 'Shutdown' 'systemctl shutdown'
