#!/usr/bin/env bash

if command -v apt-get >/dev/null 2>&1; then
    sudo sh -c "apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade && apt-get autoremove -y"
fi

if command -v yum >/dev/null 2>&1; then
    sudo sh -c "yum update -y"
fi

if command -v flatpak >/dev/null 2>&1; then
    flatpak update -y
fi

if command -v rpm-ostree >/dev/null 2>&1; then
    rpm-ostree upgrade
fi
