#!/bin/bash

xrandr --output eDP-1 --auto --primary --output DP-1-1 --auto --above eDP-1 --output DP-1-2 --auto --left-of DP-1-1

#xrandr --output eDP-1 --auto --primary --output HDMI-2 --auto --right-of eDP1


# xrandr --output eDP-1 --auto --primary
