border_width = 4
csd_border = true

csd_patterns = [
    "name=org.gnome.Nautilus",
    "class=Xdg-desktop-portal-gtk",
    "app~org.gnome",
    "app=wdisplays",
    "app=re.sonny.Junction",
    "app=org.pulseaudio.pavucontrol",
]
