[window]
decorations = "Full"
startup_mode = "Maximized"
[font]
normal = {family = "FiraCode Nerd Font", style = "Regular"}
bold = {family = "FiraCode Nerd Font", style = "Bold"}
italic = {family = "FiraCode Nerd Font", style = "Italic"}
size = 16
[mouse]
hide_when_typing = true
