theme = "catppuccin_frappe_transparent"

[editor]
line-number = "absolute"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[keys.normal]
"A-h" = "jump_view_left"
"A-j" = "jump_view_down"
"A-k" = "jump_view_up"
"A-l" = "jump_view_right"
"A-1" = "wonly"
"A-2" = "hsplit"
"A-3" = "vsplit"
"A-4" = "wclose"
