[language-server.gpt]
command = "helix-gpt"
args = ["--handler", "copilot"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "gpt" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "gpt" ]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "gpt" ]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
