#!/bin/bash

# Default location
LOCATION=$HOME/Pictures/Screenshots
if [ $# -gt 0 ]; then
    LOCATION=$1
fi

if ! [ -e $LOCATION ]; then
    mkdir -p $LOCATION
fi

if [ -f $LOCATION ]; then
    echo "$LOCATION is not a directory!"
    exit 1
fi

defaults write com.apple.screencapture location $LOCATION && \
killall SystemUIServer
